### ISSUE TITLE
let's remove the `try catch` blocks

### ISSUE THREAD

**Issue by Krastanov** [krishna-praneet/QuantumSavoryServer#1]
Currently almost all routing functions have `try catch`. Do they serve a purpose?

I suspect if these error out then the server will simply report a 50x error (as it should, and which would be more appropriate). I suspect the error message might be rendered more clearly also. If this is true and if there is no special error handling done by the current manual `try catch` blocks, I would prefer we remove them (less code is better).

Let me know if I am wrong and the server misbehaves without the `try catch`

**Comment by krishna-praneet** [comment]
The purpose is to differentiate the user errors from the actual 500 errors. If any error arises in the request processing - when I send an incomplete request body, the `json` method fails to deserialize and the server throws it as an internal server error, when in fact, the issue is due to the ill-formatted `4xx` bad request type of error from the user side. Hence the try-catch for returning the correct debug message.

**Comment by Krastanov** [comment]
Noted! Closing
